#!/bin/bash
echo "The first argument is :$1" 
echo "The second argument is : $2"
echo "The ninth argument is : $9"
echo "The tenth argument is : $10"
echo "the tenth argument is : ${10}"
echo "total number of argument is $#"

#NOTE: $10 and ${10} is different if number -ge 10 need {} (curly bracket)
