#!/bin/bash
echo -n "Is everything alright? (y/n)"
read response

if [ $response = "y" ]
then
        echo "Good to hear"
        exit
else
        echo "Sounds like and ERROR"
fi

echo "THX"
echo "Bye"

#NOTE: exit cmd inside if statement >> echo “THX” and echo “Bye” didn’t execute
