#!/bin/bash
#response=something >> no need to declare variable at the begining
echo -n "Is everything alright? (y/n)"
read response
if [ $response = "y" ]
then
        echo "Good to hear"
else
        echo "Sounds like and ERROR"
fi
echo "THX"
echo "Bye"
